### ISSUE TITLE
Inclusion of dev-only dependencies results in version conflict with existing dependencies

### ISSUE THREAD

**Issue by niketagrawal** [maxspahn/localPlannerBench#17]
Installing development-only dependencies such as pytest, black and pylint conflicts with the version of Python pinned in pyproject.toml
(python = '^3.6,<3.11'), for example, latest version of black needs python >3.6.2

**Comment by maxspahn** [comment]
Can you specify where black, pylint, pytest are required by the project? It is currently not listed as a dependency in the `pyproject.toml` file.

**Comment by niketagrawal** [comment]
> Can you specify where black, pylint, pytest are required by the project? It is currently not listed as a dependency in the `pyproject.toml` file.

Yes, these are currently not defined in pyproject.toml; these are dev-only dependencies. The potential future contributors to localplannerbench would use the poetry dev environment; it would be convenient if they can run tests locally, run static anlysis using linters, and format the code in the same dev environment. They would need to install pytest, black and pylint in the same dev environment.

**Comment by maxspahn** [comment]
Solved in 5b64427
