### ISSUE TITLE
KeyError running postProcessor tutorial example

### ISSUE THREAD

**Issue by casparvv** [maxspahn/localPlannerBench#27]
Running the example from the tutorial results in a key error for me when running the postProcessor after installing the repository with Poetry on Python 3.8.10.

The key ``interval`` can't be found, which gives an error in caseEvaluation.py at line [40](https://github.com/maxspahn/localPlannerBench/blob/25fae174e33ac43d06618dabf58e0bf7ffd9330f/plannerbenchmark/postProcessing/caseEvaluation.py#L40). 
Adding ``interval: 1`` to the [planner.yaml](https://github.com/maxspahn/localPlannerBench/blob/25fae174e33ac43d06618dabf58e0bf7ffd9330f/experiments/example/setup/planner.yaml) seems to fix the issue, I used 1 as found as a default value in the [documentation](https://maxspahn.github.io/localPlannerBench/api.html#helpers).

**Comment by casparvv** [comment]
#28 adds the ``interval: 1`` line to planner.yaml.

**Comment by maxspahn** [comment]
This  problem is only present on `main`. In the next release this is solved.
